config-version = 2
start-at-login = true
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

persistent-workspaces = ["1", "6"]
[workspace-to-monitor-force-assignment]
    6 = 'secondary'
    7 = 'secondary'

[key-mapping]
    preset = 'colemak'

[mode.main.binding]
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'
    alt-r = 'flatten-workspace-tree'
    alt-f = 'layout floating tiling'
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-ctrl-h = 'join-with left'
    alt-ctrl-j = 'join-with down'
    alt-ctrl-k = 'join-with up'
    alt-ctrl-l = 'join-with right'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
